services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    develop:
      watch:
        - action: rebuild
          path: ./backend
          ignore:
            - ./backend/main
            - ./backend/.git 