name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  GO_VERSION: "1.21"
  POSTGRES_VERSION: "15"
  REDIS_VERSION: "7"

jobs:
  # Job 1: Lint and basic checks
  lint:
    name: Lint and Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        working-directory: ./backend
        run: go mod download

      - name: Verify Go modules
        working-directory: ./backend
        run: go mod verify

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./backend
          args: --timeout=5m

      - name: Check Go formatting
        working-directory: ./backend
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "The following files are not formatted:"
            gofmt -s -l .
            exit 1
          fi

      - name: Run go vet
        working-directory: ./backend
        run: go vet ./...

  # Job 2: Build and compile check
  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        working-directory: ./backend
        run: go mod download

      - name: Build application
        working-directory: ./backend
        run: go build -v -o muse-backend .

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: muse-backend-${{ github.sha }}
          path: backend/muse-backend
          retention-days: 7

  # Job 3: Unit tests
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        working-directory: ./backend
        run: go mod download

      - name: Run unit tests
        working-directory: ./backend
        run: go test -short -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./backend/coverage.out
          flags: unittests
          name: codecov-umbrella

  # Job 4: Integration tests with database
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [lint, build]

    services:
      postgres:
        image: postgres:${{ env.POSTGRES_VERSION }}
        env:
          POSTGRES_USER: muse_user
          POSTGRES_PASSWORD: muse_password
          POSTGRES_DB: muse_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:${{ env.REDIS_VERSION }}
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        working-directory: ./backend
        run: go mod download

      - name: Install migrate tool
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin/

      - name: Run database migrations
        working-directory: ./backend
        env:
          DATABASE_URL: postgres://muse_user:muse_password@localhost:5432/muse_test?sslmode=disable
        run: |
          # Run migrations
          migrate -path migrations -database "$DATABASE_URL" up

      - name: Run integration tests
        working-directory: ./backend
        env:
          ENVIRONMENT: test
          PORT: 8080
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REDIRECT_URL: http://localhost:8080/callback
          JWT_SECRET: test-jwt-secret-for-ci-only
          # Use the test database created by the postgres service
          DATABASE_URL: postgres://muse_user:muse_password@localhost:5432/muse_test?sslmode=disable
          # Use the test redis created by the redis service
          REDIS_ADDR: localhost:6379
          REDIS_PASSWORD: ""
        run: go test -v -race -coverprofile=integration-coverage.out ./...

      - name: Upload integration test coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./backend/integration-coverage.out
          flags: integrationtests
          name: codecov-umbrella

  # Job 5: Security scanning
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install gosec
        run: go install github.com/securecodewarrior/gosec/v2/cmd/gosec@latest

      - name: Run gosec security scanner
        working-directory: ./backend
        run: gosec -fmt sarif -out gosec-report.sarif ./...

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: backend/gosec-report.sarif

  # Job 6: Docker build and push (only on main branch)
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [build, unit-tests, integration-tests]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/muse-backend
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Job 7: Deploy to staging (optional, only on main branch)
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [docker]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to staging
        run: |
          echo "🚀 Deploying to staging environment"
          echo "Image: ${{ secrets.DOCKER_USERNAME }}/muse-backend:${{ github.sha }}"
          # Add your deployment script here
          # For example, update a Kubernetes deployment, call a webhook, etc.

      - name: Run smoke tests
        run: |
          echo "🧪 Running smoke tests against staging"
          # Add smoke tests here
          # For example, check if the health endpoint returns 200

  # Job 8: Performance tests (optional)
  performance:
    name: Performance Tests
    runs-on: ubuntu-latest
    needs: [integration-tests]
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'

    services:
      postgres:
        image: postgres:${{ env.POSTGRES_VERSION }}
        env:
          POSTGRES_USER: muse_user
          POSTGRES_PASSWORD: muse_password
          POSTGRES_DB: muse_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        working-directory: ./backend
        run: go mod download

      - name: Install migrate tool
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin/

      - name: Run database migrations
        working-directory: ./backend
        env:
          DATABASE_URL: postgres://muse_user:muse_password@localhost:5432/muse_test?sslmode=disable
        run: |
          migrate -path migrations -database "$DATABASE_URL" up

      - name: Run performance benchmarks
        working-directory: ./backend
        env:
          ENVIRONMENT: test
          PORT: 8080
          SPOTIFY_CLIENT_ID: test-client-id
          SPOTIFY_CLIENT_SECRET: test-secret
          SPOTIFY_REDIRECT_URL: http://localhost:8080/callback
          JWT_SECRET: test-jwt-secret-for-ci-only
          # Use the test database created by the postgres service
          DATABASE_URL: postgres://muse_user:muse_password@localhost:5432/muse_test?sslmode=disable
          # Use the test redis created by the redis service
          REDIS_ADDR: localhost:6379
          REDIS_PASSWORD: ""
        run: |
          go test -bench=. -benchmem -run=^$ ./... | tee benchmark-results.txt

      - name: Upload benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-results-${{ github.sha }}
          path: backend/benchmark-results.txt
          retention-days: 30
